ingress:
  className: nginx

  appRoutes:
    host: app.repro.k8s.orb.local
    paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        serviceName: workspace-service
        servicePort: http
  
  apiRoutes:
    host: api.repro.k8s.orb.local
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        serviceName: api-server-service
        servicePort: http
  
  adminRoutes:
    host: admin.repro.k8s.orb.local
    paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        serviceName: admin-service
        servicePort: http
