ingress:
  className: nginx

  appRoutes:
    host: app.repro.localhost
    paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        serviceName: workspace-service
        servicePort: http
  
  apiRoutes:
    host: api.repro.localhost
    annotations:
      nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        serviceName: api-server-service
        servicePort: http
  
  adminRoutes:
    host: admin.repro.localhost
    paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        serviceName: admin-service
        servicePort: http
