id: repro/domain
language: typescript
layer: library
tags:
- type.package
tasks:
  build:
    command: pnpm run build
    deps:
    - ^:build
    inputs:
    - glob: src/**/*.tdls
      cache: true
    outputs:
    - src/generated/**/*
    options:
      cache: true
toolchain:
  default: node
