id: repro/devtools-demo
language: typescript
layer: application
tags:
- type.app
- build.static
tasks:
  build:
    command: pnpm run build
    deps:
    - ^:build
    outputs:
    - dist
    options:
      cache: true
  serve:
    command: pnpm run serve
    deps:
    - ^:build
toolchain:
  default: node
